---
deployment:
  tasks:
    - export COMPOSER_HOME="${HOME}/.composer"
    - php "${DEPLOYPATH}/composer.phar" install --no-dev --optimize-autoloader --no-interaction
    - mkdir -p "${DEPLOYPATH}/uploads"
    - chmod 755 "${DEPLOYPATH}/uploads"